### ISSUE TITLE
Mobile Development

### ISSUE THREAD

**Issue by mtachaudhary** [mtachaudhary/ribbash-digital#3]
Please done following tasks

**Comment by mtachaudhary** [comment]
Replace Familiarity with the latest technology icon, Designer will provide it.

**Comment by mtachaudhary** [comment]
- [x] Change title to “Custom Web Development” and Description would be “Ribbash for feature-packed Mobile experience We offer Top-Notch Solutions regarding mobile applications”
- [x] Replace Familiarity with the latest technology icon, Shawaiz will provide you.

**Comment by mzadeveloper** [comment]
> * [ ]  Change title to “Custom Web Development” and Description would be “Ribbash for feature-packed Mobile experience We offer Top-Notch Solutions regarding mobile applications”
> * [ ]  Replace Familiarity with the latest technology icon, Shawaiz will provide you.

hello

**Comment by mzadeveloper** [comment]
Hello gen
